<template>
  <div class="lens-app" @dragover.prevent="onAppDragOver" @dragleave.self="onAppDragLeave" @drop.prevent="onAppDrop">

    <!-- Header -->
    <header class="lens-header">
      <div class="header-left">
        <span class="logo-icon">🔭</span>
        <div class="brand">
          <span class="brand-conway">Conway</span><span class="brand-lens">Lens</span>
        </div>
        <span class="brand-tagline">Team boundary analysis via git history</span>
      </div>
      <div class="header-right">
        <div v-if="dateInfo" class="date-info">
          <span class="date-info-label">Data range:</span>
          <span class="date-info-value">{{ dateInfo.since }} → {{ dateInfo.until }}</span>
        </div>
        <div v-if="loadedFilename" class="filename-chip" :title="loadedFilename">
          📄 {{ loadedFilename }}
        </div>
        <label class="load-btn" title="Load a TimelineData.csv file">
          {{ dataLoaded ? '↺ Load file' : '📂 Load CSV' }}
          <input type="file" accept=".csv" class="hidden-input" @change="onFileInput" />
        </label>
      </div>
    </header>

    <!-- Main content -->
    <main class="lens-main">

      <!-- Upload zone (no data yet) -->
      <div v-if="!dataLoaded" class="upload-zone" :class="{ 'drag-over': isDragOver }" @click="triggerFileInput">
        <div class="upload-icon">{{ isDragOver ? '📥' : '📂' }}</div>
        <h2 class="upload-title">{{ isDragOver ? 'Drop to load' : 'Load TimelineData.csv' }}</h2>
        <p class="upload-hint">Drag &amp; drop your CSV here, or click to browse</p>
        <p class="upload-sub">Generated by <code>analysis/Analyse-Repositories.ps1</code></p>
        <div v-if="dataError" class="error-box">
          <strong>Error:</strong> {{ dataError }}
        </div>
        <input ref="hiddenInputRef" type="file" accept=".csv" class="hidden-input" @change="onFileInput" />
      </div>

      <!-- Full-screen drag overlay when data is already shown -->
      <transition name="overlay-fade">
        <div v-if="dataLoaded && isDragOver" class="drag-overlay">
          <div class="drag-overlay-content">
            <div class="upload-icon">📥</div>
            <p>Drop to replace data</p>
          </div>
        </div>
      </transition>

      <!-- Graph view -->
      <div v-if="dataLoaded" class="graph-container">
        <NetworkGraph />
      </div>
    </main>

    <!-- Floating panels -->
    <FilterPanel v-if="dataLoaded" />
    <MappingEditor />
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { storeToRefs } from 'pinia';
import { useLensStore } from '../stores/useLensStore';
import NetworkGraph from '../components/NetworkGraph.vue';
import FilterPanel from '../components/FilterPanel.vue';
import MappingEditor from '../components/MappingEditor.vue';

const store = useLensStore();
const { dataLoaded, dataError, dateInfo } = storeToRefs(store);

const loadedFilename = ref('');
const isDragOver = ref(false);
const hiddenInputRef = ref(null);

async function loadFile(file) {
  if (!file || !file.name.endsWith('.csv')) return;
  loadedFilename.value = file.name;
  await store.loadTimelineData(file);
}

function onFileInput(event) {
  const file = event.target.files?.[0];
  if (file) loadFile(file);
  event.target.value = '';
}

function triggerFileInput() {
  hiddenInputRef.value?.click();
}

let dragCounter = 0;

function onAppDragOver(event) {
  if ([...event.dataTransfer.items].some(i => i.kind === 'file')) {
    isDragOver.value = true;
  }
}

function onAppDragLeave() {
  dragCounter--;
  if (dragCounter <= 0) { dragCounter = 0; isDragOver.value = false; }
}

function onAppDrop(event) {
  dragCounter = 0;
  isDragOver.value = false;
  const file = event.dataTransfer.files?.[0];
  if (file) loadFile(file);
}
</script>

<style scoped>
.lens-app {
  @apply flex flex-col min-h-screen bg-gray-50 relative;
}

.lens-header {
  @apply bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between shadow-sm flex-shrink-0;
}

.header-left {
  @apply flex items-center gap-4;
}

.logo-icon {
  @apply text-2xl;
}

.brand {
  @apply text-xl font-extrabold tracking-tight;
}

.brand-conway {
  color: var(--brand-blue);
}

.brand-lens {
  color: var(--brand-teal);
}

.brand-tagline {
  @apply text-sm text-gray-400 hidden sm:block;
}

.header-right {
  @apply flex items-center gap-3;
}

.date-info {
  @apply flex items-center gap-2 text-sm text-gray-500;
}

.date-info-label {
  @apply font-medium;
}

.date-info-value {
  @apply font-mono text-brand-blue;
}

.filename-chip {
  @apply text-xs text-gray-500 bg-gray-100 border border-gray-200 rounded-full px-3 py-1 max-w-[180px] truncate;
}

.load-btn {
  @apply flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold bg-brand-blue text-white hover:bg-brand-blue-dark transition-all duration-150 cursor-pointer;
}

.hidden-input {
  @apply hidden;
}

.lens-main {
  @apply flex-1 flex flex-col p-6 relative;
}

/* Upload zone */
.upload-zone {
  @apply flex-1 flex flex-col items-center justify-center gap-4 text-center
         border-2 border-dashed border-gray-300 rounded-2xl cursor-pointer
         transition-all duration-200 hover:border-brand-blue hover:bg-blue-50/30;
  min-height: 400px;
}

.upload-zone.drag-over {
  @apply border-brand-orange bg-orange-50/40 scale-[1.01];
}

.upload-icon {
  @apply text-6xl;
}

.upload-title {
  @apply text-2xl font-bold text-gray-500;
}

.upload-hint {
  @apply text-gray-400 text-sm;
}

.upload-sub {
  @apply text-xs text-gray-300;
}

.upload-sub code {
  @apply bg-gray-100 px-1.5 py-0.5 rounded font-mono text-brand-blue;
}

.error-box {
  @apply bg-red-50 border border-red-200 rounded-lg px-4 py-3 text-sm text-red-700 max-w-md;
}

/* Full-screen drag overlay */
.drag-overlay {
  @apply absolute inset-0 z-30 bg-brand-orange/10 backdrop-blur-sm
         border-2 border-dashed border-brand-orange rounded-xl
         flex items-center justify-center pointer-events-none;
}

.drag-overlay-content {
  @apply flex flex-col items-center gap-3 text-brand-orange font-bold text-xl;
}

.overlay-fade-enter-active, .overlay-fade-leave-active { transition: opacity 0.15s ease; }
.overlay-fade-enter-from, .overlay-fade-leave-to { opacity: 0; }

.graph-container {
  @apply flex-1;
}
</style>
