<template>
  <div class="lens-app" @dragover.prevent="onAppDragOver" @dragleave.self="onAppDragLeave" @drop.prevent="onAppDrop">

    <!-- Header -->
    <header class="lens-header">
      <div class="header-left">
        <span class="logo-icon">🔭</span>
        <div class="brand">
          <span class="brand-conway">Conway</span><span class="brand-lens">Lens</span>
        </div>
        <span class="brand-tagline">Team boundary analysis via git history</span>
      </div>
      <div class="header-right">
        <button
          v-if="activeLensName"
          class="active-lens-chip"
          @click="store.uiLensOpen = true"
          :title="`Active lens: ${activeLensName}`"
        >
          <Telescope :size="13" />
          <span class="truncate">{{ activeLensName }}</span>
        </button>
        <div v-if="dateInfo" class="date-info">
          <span class="date-info-label">Data range:</span>
          <span class="date-info-value">{{ dateInfo.since }} → {{ dateInfo.until }}</span>
        </div>
        <div v-if="loadedFilenames.length" class="filename-chip" :title="loadedFilenames.join('\n')">
          <FileText :size="14" />
          <span class="truncate">{{ loadedFilenames.length === 1 ? loadedFilenames[0] : `${loadedFilenames.length} files` }}</span>
        </div>
        <button v-if="dataLoaded" class="new-scenario-btn" @click="onClear">
          <FlaskConical :size="16" /> New scenario
        </button>
        <label v-if="dataLoaded" class="load-btn-secondary" title="Merge additional CSV files into the current dataset">
          <Plus :size="16" /> Add CSV
          <input type="file" accept=".csv" multiple class="hidden-input" @change="e => onFileInput(e, true)" />
        </label>
        <label class="load-btn" title="Load one or more commit history CSV files">
          <component :is="dataLoaded ? RefreshCw : FolderOpen" :size="16" />
          {{ dataLoaded ? 'Replace' : 'Load CSV' }}
          <input type="file" accept=".csv" multiple class="hidden-input" @change="e => onFileInput(e, false)" />
        </label>
      </div>
    </header>

    <!-- Main content -->
    <main class="lens-main">

      <!-- Landing: two-column upload / simulate -->
      <div v-if="!dataLoaded" class="landing-grid">

        <!-- Upload card -->
        <div class="upload-zone" :class="{ 'drag-over': isDragOver }" @click="triggerFileInput">
          <component :is="isDragOver ? Inbox : FolderOpen" :size="64" class="upload-icon" :stroke-width="1.5" />
          <h2 class="upload-title">{{ isDragOver ? 'Drop to load' : 'Load commit history CSV' }}</h2>
          <p class="upload-hint">Drag &amp; drop one or more CSV files here, or click to browse</p>
          <p class="upload-sub">Generated by <code>cli/extract-git-history.mjs</code> or <code>cli/extract-git-history.ps1</code></p>
          <div v-if="dataError" class="error-box">
            <strong>Error:</strong> {{ dataError }}
          </div>
          <input ref="hiddenInputRef" type="file" accept=".csv" multiple class="hidden-input" @change="e => onFileInput(e, false)" />
        </div>

        <!-- Divider -->
        <div class="landing-divider"><span>or</span></div>

        <SimulateCard @simulated="loadedFilenames = []" />
      </div>

      <!-- Full-screen drag overlay when data is already shown -->
      <transition name="overlay-fade">
        <div v-if="dataLoaded && isDragOver" class="drag-overlay">
          <div class="drag-overlay-content">
            <Inbox :size="64" class="upload-icon" :stroke-width="1.5" />
            <p>Drop to merge into current data</p>
            <p class="drag-overlay-hint">Hold <kbd>Shift</kbd> to replace instead</p>
          </div>
        </div>
      </transition>

      <!-- Graph view -->
      <div v-if="dataLoaded" class="graph-container">
        <NetworkGraph />
      </div>
    </main>

    <MappingEditor />
    <FilterPanel />
    <LensManager />
    <MappingSpotlight />

  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { storeToRefs } from 'pinia';
import { useLensStore } from '../stores/useLensStore';
import NetworkGraph from '../components/NetworkGraph.vue';
import MappingEditor from '../components/MappingEditor.vue';
import FilterPanel from '../components/FilterPanel.vue';
import LensManager from '../components/LensManager.vue';
import MappingSpotlight from '../components/MappingSpotlight.vue';
import SimulateCard from '../simulation/SimulateCard.vue';
import {
  FolderOpen, Inbox, FlaskConical, Plus, RefreshCw, FileText, Telescope,
} from '@lucide/vue';

const store = useLensStore();
const { dataLoaded, dataError, dateInfo, lenses, activeLensId } = storeToRefs(store);

const activeLensName = computed(() =>
  lenses.value.find(l => l.id === activeLensId.value)?.name ?? null
);

const loadedFilenames = ref([]);
const isDragOver = ref(false);
const hiddenInputRef = ref(null);

function onClear() {
  store.clearData();
  loadedFilenames.value = [];
}

async function loadFiles(files, { append = false } = {}) {
  const csvs = [...files].filter(f => f && f.name.endsWith('.csv'));
  if (csvs.length === 0) return;
  await store.loadCommits(csvs, { append });
  if (store.dataError) return;
  loadedFilenames.value = append
    ? [...loadedFilenames.value, ...csvs.map(f => f.name)]
    : csvs.map(f => f.name);
}

function onFileInput(event, append) {
  const files = event.target.files;
  if (files?.length) loadFiles(files, { append: append && dataLoaded.value });
  event.target.value = '';
}

function triggerFileInput() {
  hiddenInputRef.value?.click();
}

let dragCounter = 0;

function onAppDragOver(event) {
  if ([...event.dataTransfer.items].some(i => i.kind === 'file')) {
    isDragOver.value = true;
  }
}

function onAppDragLeave() {
  dragCounter--;
  if (dragCounter <= 0) { dragCounter = 0; isDragOver.value = false; }
}

function onAppDrop(event) {
  dragCounter = 0;
  isDragOver.value = false;
  const files = event.dataTransfer.files;
  if (!files?.length) return;
  // While data is already loaded, drop merges; hold Shift to replace.
  const append = dataLoaded.value && !event.shiftKey;
  loadFiles(files, { append });
}
</script>

<style scoped>
.lens-app {
  @apply flex flex-col min-h-screen bg-gray-50 relative;
}

.lens-header {
  @apply bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between shadow-sm flex-shrink-0;
}

.header-left {
  @apply flex items-center gap-4;
}

.logo-icon {
  @apply text-2xl;
}

.brand {
  @apply text-xl font-extrabold tracking-tight;
}

.brand-conway {
  color: var(--brand-blue);
}

.brand-lens {
  color: var(--brand-teal);
}

.brand-tagline {
  @apply text-sm text-gray-400 hidden sm:block;
}

.header-right {
  @apply flex items-center gap-3;
}

.date-info {
  @apply flex items-center gap-2 text-sm text-gray-500;
}

.date-info-label {
  @apply font-medium;
}

.date-info-value {
  @apply font-mono text-brand-blue;
}

.filename-chip {
  @apply inline-flex items-center gap-1.5 text-xs text-gray-500 bg-gray-100 border border-gray-200 rounded-full px-3 py-1 max-w-[200px];
}

.active-lens-chip {
  @apply inline-flex items-center gap-1.5 text-xs font-semibold text-brand-teal
         bg-teal-50 border border-brand-teal/30 rounded-full px-3 py-1 max-w-[160px]
         cursor-pointer hover:bg-teal-100 transition-colors duration-150;
}

.new-scenario-btn {
  @apply flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold border border-gray-200 text-gray-500 bg-white hover:border-brand-teal hover:text-brand-teal transition-all duration-150 cursor-pointer;
}

.load-btn {
  @apply flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold bg-brand-blue text-white hover:bg-brand-blue-dark transition-all duration-150 cursor-pointer;
}

.load-btn-secondary {
  @apply flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold border border-brand-teal text-brand-teal bg-white hover:bg-teal-50 transition-all duration-150 cursor-pointer;
}

.drag-overlay-hint {
  @apply text-sm font-normal text-brand-orange/80;
}
.drag-overlay-hint kbd {
  @apply px-1.5 py-0.5 rounded border border-brand-orange/40 bg-white/60 font-mono text-xs;
}

.hidden-input {
  @apply hidden;
}

.lens-main {
  @apply flex-1 flex flex-col p-6 relative;
}

/* Landing two-column layout */
.landing-grid {
  @apply flex-1 flex items-stretch gap-0;
  min-height: 400px;
}

.landing-divider {
  @apply flex flex-col items-center justify-center flex-shrink-0 px-4 text-gray-300 font-semibold text-sm select-none;
}
.landing-divider span {
  @apply bg-gray-50 px-2 py-1 rounded-full z-10;
}

/* Upload zone */
.upload-zone {
  @apply flex-1 flex flex-col items-center justify-center gap-4 text-center
         border-2 border-dashed border-gray-300 rounded-2xl cursor-pointer
         transition-all duration-200 hover:border-brand-blue hover:bg-blue-50/30;
}

.upload-zone.drag-over {
  @apply border-brand-orange bg-orange-50/40 scale-[1.01];
}

.upload-icon {
  @apply text-gray-400;
}

.upload-title {
  @apply text-2xl font-bold text-gray-500;
}

.upload-hint {
  @apply text-gray-400 text-sm;
}

.upload-sub {
  @apply text-xs text-gray-300;
}

.upload-sub code {
  @apply bg-gray-100 px-1.5 py-0.5 rounded font-mono text-brand-blue;
}

.error-box {
  @apply bg-red-50 border border-red-200 rounded-lg px-4 py-3 text-sm text-red-700 max-w-md;
}

/* Full-screen drag overlay */
.drag-overlay {
  @apply absolute inset-0 z-30 bg-brand-orange/10 backdrop-blur-sm
         border-2 border-dashed border-brand-orange rounded-xl
         flex items-center justify-center pointer-events-none;
}

.drag-overlay-content {
  @apply flex flex-col items-center gap-3 text-brand-orange font-bold text-xl;
}

.overlay-fade-enter-active, .overlay-fade-leave-active { transition: opacity 0.15s ease; }
.overlay-fade-enter-from, .overlay-fade-leave-to { opacity: 0; }


.graph-container {
  @apply flex-1;
}

</style>
