<template>
  <div class="lens-app" @dragover.prevent="onAppDragOver" @dragleave.self="onAppDragLeave" @drop.prevent="onAppDrop">

    <!-- Header -->
    <header class="lens-header">
      <div class="header-left">
        <span class="logo-icon">🔭</span>
        <div class="brand">
          <span class="brand-conway">Conway</span><span class="brand-lens">Lens</span>
        </div>
        <span class="brand-tagline">Team boundary analysis via git history</span>
      </div>
      <div class="header-right">
        <div v-if="dateInfo" class="date-info">
          <span class="date-info-label">Data range:</span>
          <span class="date-info-value">{{ dateInfo.since }} → {{ dateInfo.until }}</span>
        </div>
        <div v-if="loadedFilenames.length" class="filename-chip" :title="loadedFilenames.join('\n')">
          <FileText :size="14" />
          <span class="truncate">{{ loadedFilenames.length === 1 ? loadedFilenames[0] : `${loadedFilenames.length} files` }}</span>
        </div>
        <button v-if="dataLoaded" class="new-scenario-btn" @click="onClear">
          <FlaskConical :size="16" /> New scenario
        </button>
        <label v-if="dataLoaded" class="load-btn-secondary" title="Merge additional CSV files into the current dataset">
          <Plus :size="16" /> Add CSV
          <input type="file" accept=".csv" multiple class="hidden-input" @change="e => onFileInput(e, true)" />
        </label>
        <label class="load-btn" title="Load one or more commit history CSV files">
          <component :is="dataLoaded ? RefreshCw : FolderOpen" :size="16" />
          {{ dataLoaded ? 'Replace' : 'Load CSV' }}
          <input type="file" accept=".csv" multiple class="hidden-input" @change="e => onFileInput(e, false)" />
        </label>
      </div>
    </header>

    <!-- Main content -->
    <main class="lens-main">

      <!-- Landing: two-column upload / simulate -->
      <div v-if="!dataLoaded" class="landing-grid">

        <!-- Upload card -->
        <div class="upload-zone" :class="{ 'drag-over': isDragOver }" @click="triggerFileInput">
          <component :is="isDragOver ? Inbox : FolderOpen" :size="64" class="upload-icon" :stroke-width="1.5" />
          <h2 class="upload-title">{{ isDragOver ? 'Drop to load' : 'Load commit history CSV' }}</h2>
          <p class="upload-hint">Drag &amp; drop one or more CSV files here, or click to browse</p>
          <p class="upload-sub">Generated by <code>cli/extract-git-history.mjs</code> or <code>cli/extract-git-history.ps1</code></p>
          <div v-if="dataError" class="error-box">
            <strong>Error:</strong> {{ dataError }}
          </div>
          <input ref="hiddenInputRef" type="file" accept=".csv" multiple class="hidden-input" @change="e => onFileInput(e, false)" />
        </div>

        <!-- Divider -->
        <div class="landing-divider"><span>or</span></div>

        <!-- Simulate card -->
        <div class="simulate-card">
          <div class="sim-header">
            <FlaskConical :size="36" class="sim-icon" :stroke-width="1.5" />
            <div>
              <h2 class="sim-title">Simulate a scenario</h2>
              <p class="sim-subtitle">Generate random contribution data on the fly</p>
            </div>
          </div>

          <div class="sim-controls">
            <div class="sim-row">
              <label class="sim-label">Authors</label>
              <span class="sim-value">{{ simAuthors }}</span>
            </div>
            <input type="range" class="sim-slider" min="3" max="26" v-model.number="simAuthors" />

            <div class="sim-row">
              <label class="sim-label">Repositories</label>
              <span class="sim-value">{{ simRepos }}</span>
            </div>
            <input type="range" class="sim-slider" min="2" max="20" v-model.number="simRepos" />

            <div class="sim-row">
              <label class="sim-label">Commits per active pair</label>
              <span class="sim-value">{{ simMin }} – {{ simMax }}</span>
            </div>
            <div class="sim-range-row">
              <input type="range" class="sim-slider" min="1" max="200"
                     :value="simMin" @input="e => simMin = Math.min(+e.target.value, simMax)" />
              <input type="range" class="sim-slider" min="1" max="500"
                     :value="simMax" @input="e => simMax = Math.max(+e.target.value, simMin)" />
            </div>
          </div>

          <button class="sim-btn" @click.stop="generate">Generate</button>
        </div>
      </div>

      <!-- Full-screen drag overlay when data is already shown -->
      <transition name="overlay-fade">
        <div v-if="dataLoaded && isDragOver" class="drag-overlay">
          <div class="drag-overlay-content">
            <Inbox :size="64" class="upload-icon" :stroke-width="1.5" />
            <p>Drop to merge into current data</p>
            <p class="drag-overlay-hint">Hold <kbd>Shift</kbd> to replace instead</p>
          </div>
        </div>
      </transition>

      <!-- Graph view -->
      <div v-if="dataLoaded" class="graph-container">
        <NetworkGraph />
      </div>
    </main>

    <MappingEditor />
    <FilterPanel />

    <!-- Sim overwrite confirmation dialog -->
    <teleport to="body">
      <div v-if="showSimConfirm" class="sim-confirm-backdrop" @click.self="cancelSim">
        <div class="sim-confirm-dialog" role="dialog" aria-modal="true">
          <h3 class="sim-confirm-title">Replace team mappings?</h3>
          <p class="sim-confirm-body">
            Generating a simulation will overwrite your current team configuration with
            auto-generated teams. This cannot be undone.
          </p>
          <p class="sim-confirm-hint">
            Export your mappings first so you can restore them later.
          </p>
          <div class="sim-confirm-actions">
            <button class="sim-export-btn" @click="exportMappings">
              <Download :size="14" /> Export mappings
            </button>
            <div class="sim-confirm-right">
              <button class="sim-cancel-btn" @click="cancelSim">Cancel</button>
              <button class="sim-proceed-btn" @click="confirmSim">Generate anyway</button>
            </div>
          </div>
        </div>
      </div>
    </teleport>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { storeToRefs } from 'pinia';
import { useLensStore } from '../stores/useLensStore';
import NetworkGraph from '../components/NetworkGraph.vue';
import MappingEditor from '../components/MappingEditor.vue';
import FilterPanel from '../components/FilterPanel.vue';
import {
  FolderOpen, Inbox, FlaskConical, Plus, RefreshCw, FileText, Download,
} from '@lucide/vue';

const store = useLensStore();
const { dataLoaded, dataError, dateInfo, teams } = storeToRefs(store);

const loadedFilenames = ref([]);
const isDragOver = ref(false);
const hiddenInputRef = ref(null);

// Simulation state
const simAuthors = ref(8);
const simRepos   = ref(5);
const simMin     = ref(5);
const simMax     = ref(50);
const showSimConfirm = ref(false);
const pendingSimParams = ref(null);

function hasUserTeams() {
  return teams.value.some(t => !t.id.startsWith('sim-team-'));
}

function generate() {
  const params = {
    authorCount: simAuthors.value,
    repoCount:   simRepos.value,
    minCommits:  simMin.value,
    maxCommits:  simMax.value,
  };
  if (hasUserTeams()) {
    pendingSimParams.value = params;
    showSimConfirm.value = true;
    return;
  }
  runSimulation(params);
}

function runSimulation(params) {
  store.loadSimulatedData(params);
  loadedFilenames.value = [];
  showSimConfirm.value = false;
  pendingSimParams.value = null;
}

function confirmSim() {
  if (pendingSimParams.value) runSimulation(pendingSimParams.value);
}

function cancelSim() {
  showSimConfirm.value = false;
  pendingSimParams.value = null;
}

function exportMappings() {
  const blob = new Blob([store.exportMappings()], { type: 'application/json' });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: 'conwaylens-mappings.json' });
  a.click();
  URL.revokeObjectURL(url);
}

function onClear() {
  store.clearData();
  loadedFilenames.value = [];
}

async function loadFiles(files, { append = false } = {}) {
  const csvs = [...files].filter(f => f && f.name.endsWith('.csv'));
  if (csvs.length === 0) return;
  await store.loadCommits(csvs, { append });
  if (store.dataError) return;
  loadedFilenames.value = append
    ? [...loadedFilenames.value, ...csvs.map(f => f.name)]
    : csvs.map(f => f.name);
}

function onFileInput(event, append) {
  const files = event.target.files;
  if (files?.length) loadFiles(files, { append: append && dataLoaded.value });
  event.target.value = '';
}

function triggerFileInput() {
  hiddenInputRef.value?.click();
}

let dragCounter = 0;

function onAppDragOver(event) {
  if ([...event.dataTransfer.items].some(i => i.kind === 'file')) {
    isDragOver.value = true;
  }
}

function onAppDragLeave() {
  dragCounter--;
  if (dragCounter <= 0) { dragCounter = 0; isDragOver.value = false; }
}

function onAppDrop(event) {
  dragCounter = 0;
  isDragOver.value = false;
  const files = event.dataTransfer.files;
  if (!files?.length) return;
  // While data is already loaded, drop merges; hold Shift to replace.
  const append = dataLoaded.value && !event.shiftKey;
  loadFiles(files, { append });
}
</script>

<style scoped>
.lens-app {
  @apply flex flex-col min-h-screen bg-gray-50 relative;
}

.lens-header {
  @apply bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between shadow-sm flex-shrink-0;
}

.header-left {
  @apply flex items-center gap-4;
}

.logo-icon {
  @apply text-2xl;
}

.brand {
  @apply text-xl font-extrabold tracking-tight;
}

.brand-conway {
  color: var(--brand-blue);
}

.brand-lens {
  color: var(--brand-teal);
}

.brand-tagline {
  @apply text-sm text-gray-400 hidden sm:block;
}

.header-right {
  @apply flex items-center gap-3;
}

.date-info {
  @apply flex items-center gap-2 text-sm text-gray-500;
}

.date-info-label {
  @apply font-medium;
}

.date-info-value {
  @apply font-mono text-brand-blue;
}

.filename-chip {
  @apply inline-flex items-center gap-1.5 text-xs text-gray-500 bg-gray-100 border border-gray-200 rounded-full px-3 py-1 max-w-[200px];
}

.new-scenario-btn {
  @apply flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold border border-gray-200 text-gray-500 bg-white hover:border-brand-teal hover:text-brand-teal transition-all duration-150 cursor-pointer;
}

.load-btn {
  @apply flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold bg-brand-blue text-white hover:bg-brand-blue-dark transition-all duration-150 cursor-pointer;
}

.load-btn-secondary {
  @apply flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold border border-brand-teal text-brand-teal bg-white hover:bg-teal-50 transition-all duration-150 cursor-pointer;
}

.drag-overlay-hint {
  @apply text-sm font-normal text-brand-orange/80;
}
.drag-overlay-hint kbd {
  @apply px-1.5 py-0.5 rounded border border-brand-orange/40 bg-white/60 font-mono text-xs;
}

.hidden-input {
  @apply hidden;
}

.lens-main {
  @apply flex-1 flex flex-col p-6 relative;
}

/* Landing two-column layout */
.landing-grid {
  @apply flex-1 flex items-stretch gap-0;
  min-height: 400px;
}

.landing-divider {
  @apply flex flex-col items-center justify-center flex-shrink-0 px-4 text-gray-300 font-semibold text-sm select-none;
}
.landing-divider span {
  @apply bg-gray-50 px-2 py-1 rounded-full z-10;
}

/* Upload zone */
.upload-zone {
  @apply flex-1 flex flex-col items-center justify-center gap-4 text-center
         border-2 border-dashed border-gray-300 rounded-2xl cursor-pointer
         transition-all duration-200 hover:border-brand-blue hover:bg-blue-50/30;
}

.upload-zone.drag-over {
  @apply border-brand-orange bg-orange-50/40 scale-[1.01];
}

.upload-icon {
  @apply text-gray-400;
}

.upload-title {
  @apply text-2xl font-bold text-gray-500;
}

.upload-hint {
  @apply text-gray-400 text-sm;
}

.upload-sub {
  @apply text-xs text-gray-300;
}

.upload-sub code {
  @apply bg-gray-100 px-1.5 py-0.5 rounded font-mono text-brand-blue;
}

.error-box {
  @apply bg-red-50 border border-red-200 rounded-lg px-4 py-3 text-sm text-red-700 max-w-md;
}

/* Full-screen drag overlay */
.drag-overlay {
  @apply absolute inset-0 z-30 bg-brand-orange/10 backdrop-blur-sm
         border-2 border-dashed border-brand-orange rounded-xl
         flex items-center justify-center pointer-events-none;
}

.drag-overlay-content {
  @apply flex flex-col items-center gap-3 text-brand-orange font-bold text-xl;
}

.overlay-fade-enter-active, .overlay-fade-leave-active { transition: opacity 0.15s ease; }
.overlay-fade-enter-from, .overlay-fade-leave-to { opacity: 0; }

/* Sim overwrite confirmation dialog */
.sim-confirm-backdrop {
  @apply fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm;
}

.sim-confirm-dialog {
  @apply bg-white rounded-2xl shadow-2xl p-6 max-w-sm w-full mx-4 flex flex-col gap-3;
}

.sim-confirm-title {
  @apply text-base font-bold text-gray-800;
}

.sim-confirm-body {
  @apply text-sm text-gray-600;
}

.sim-confirm-hint {
  @apply text-sm font-semibold;
  color: var(--brand-orange);
}

.sim-confirm-actions {
  @apply flex items-center justify-between gap-3 mt-1 flex-wrap;
}

.sim-confirm-right {
  @apply flex items-center gap-2 ml-auto;
}

.sim-export-btn {
  @apply flex items-center gap-1.5 text-sm font-semibold px-3 py-1.5 rounded-lg border transition-all duration-150;
  color: var(--brand-teal);
  border-color: var(--brand-teal);
  background: white;
}
.sim-export-btn:hover { background: #f0fafa; }

.sim-cancel-btn {
  @apply text-sm font-semibold px-3 py-1.5 rounded-lg border border-gray-200 text-gray-500 bg-white hover:border-gray-300 transition-all duration-150;
}

.sim-proceed-btn {
  @apply text-sm font-bold px-4 py-1.5 rounded-lg text-white transition-all duration-150;
  background: var(--brand-orange);
}
.sim-proceed-btn:hover { filter: brightness(0.9); }

.graph-container {
  @apply flex-1;
}

/* Simulate card */
.simulate-card {
  @apply flex-1 flex flex-col gap-5 justify-center px-10 py-8
         border-2 border-dashed border-gray-200 rounded-2xl
         transition-all duration-200 hover:border-brand-teal hover:bg-teal-50/20;
}

.sim-header {
  @apply flex items-center gap-3;
}

.sim-icon {
  @apply text-brand-teal;
}

.sim-title {
  @apply text-xl font-bold text-gray-600;
}

.sim-subtitle {
  @apply text-sm text-gray-400 mt-0.5;
}

.sim-controls {
  @apply flex flex-col gap-1.5;
}

.sim-row {
  @apply flex items-center justify-between mt-2;
}

.sim-label {
  @apply text-sm font-semibold text-gray-500;
}

.sim-value {
  @apply text-sm font-mono font-bold text-brand-blue tabular-nums;
}

.sim-slider {
  @apply w-full h-1.5 rounded-full appearance-none cursor-pointer;
  accent-color: #088F9B;
}

.sim-range-row {
  @apply flex flex-col gap-1.5;
}

.sim-btn {
  @apply mt-2 px-6 py-2.5 rounded-xl text-sm font-bold text-white transition-all duration-150 self-start;
  background: #088F9B;
}
.sim-btn:hover {
  background: #067a85;
}
</style>
